FROM golang:1.8.3-alpine

ARG WORKDIR=/go/src/github.com/vterdunov/docktor

WORKDIR $WORKDIR

RUN apk add --no-cache git build-base
RUN go get -v github.com/golang/dep/cmd/dep

# Debugger
RUN go get -v github.com/derekparker/delve/cmd/dlv

COPY . $WORKDIR
RUN [ -d 'vendor' ] || make dep

RUN make compile

CMD dlv debug --headless=true --listen=localhost:2345 --api-version=2 --log=true --
